# Generated by Django 5.1.5 on 2025-07-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_gram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='gram',
            new_name='minimum',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=2925, max_digits=10),
            preserve_default=False,
        ),
    ]
