# Generated by Django 5.1.5 on 2025-07-20 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_gram_product_minimum_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='minimum',
        ),
    ]
